### ISSUE TITLE
Question for the performance evaluation.

### ISSUE THREAD

**Issue by haoyu-wangg** [inoue0426/scVGAE#1]
I read your paper on arxiv titled "scVGAE: A Novel Approach using ZINB-Based Variational Graph Autoencoder for Single-Cell RNA-Seq Imputation". I have a question regarding the performance evaluation. The GNNImpute method uses a semi-supervised learning approach to recover from dropout events. According to the standard procedure in the GNNImpute paper, the data should be split into training, validation, and test sets in a 6:2:2 ratio. I would like to know how the data was split and compared with GNNImpute in your paper's evaluation process, or how GNNImpute was used.

**Comment by inoue0426** [comment]
Hi @haoyu-wangg 

This is the code for GNNImpute.
https://github.com/inoue0426/scVGAE-paper/blob/main/cell%20clustering/GNNImpute.ipynb

I followed the instruction from the GNNImpute github. https://github.com/Lav-i/GNNImpute?tab=readme-ov-file#quick-start

This means that I just utilized the generalized parameter from their setting.

If you have any questions, please let me know.
